### ISSUE TITLE
Add event for paste complete

### ISSUE THREAD

**Issue by alanasim** [ag-grid/ag-grid-enterprise#142]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

During multiple cell range paste the grid fires a cellValueChanged event for each individual cell but there is no distinct signal for range paste completion

**Desired behavior**

Emit event once all range paste cell values have been changed in the grid with data for changed rows.

**Currently using:**
ag-grid 12.0.2
ag-grid-enterprise 12.0.2
ag-grid-react 12.0.0
react ^15.5.4
redux ^3.6.0

**What is the motivation / use case for changing the behavior?**

Was having serious performance issues with multiple cell range paste in ag-grid in a React-Redux application (5+ second lags) even with deltaRowDataMode, immutableJS, and other optimizations. Traced the issue to relying on cellValueChanged for updating rowData in Redux store, which resulted in clipboardService.multipleCellRange running for each cell in the paste. The best way I found around this was to ensure only a single Redux update per range paste by listening for the cellsFlashed event. Which works well, but a specific paste event with included updated grid data in the params would be great.

Unless there's a strategy I'm missing out on, this would probably be useful for others using Redux with ag-grid as it seems like using cellValueChanged is a common pattern but causes issues in this situation.

Happy to help reproduce the performance issue if that would be helpful, let me know.

**Comment by seanlandsman** [comment]
Hi,

Can you please post this in our members forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5

This sounds like a good use case for us - we can work with you to improve our react offering

If you dont have access to the forum please email accounts@ag-grid.com (along with your license key) and they'll grant you access

thanks

**Comment by chadbr** [comment]
is there a enhancement ID for this?

**Comment by cjtafoya** [comment]
Following up as well; this is quite important to us and per the forum discussion below I don't see the ticket in the pipeline. Any update would be appreciated.

https://ag-grid.com/forum/showthread.php?tid=6582

**Comment by makinggoodsoftware** [comment]
Hi,

This is tracked by AG-1034

Since this can be tracked from our pipeline we are going to close this issue

https://www.ag-grid.com/ag-grid-pipeline/



===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months.

As a result, we don’t have capacity to take feature requests from GitHub.e

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by jordangotbaum** [comment]
@alanasim How did you find the cellsFlashed event? Couldn't find it in the grid events reference. Any chance you could provide some code? :sweat_smile:
