### ISSUE TITLE
Expanding group node doesn't resolve loading when the user quickly collapse/expand a node

### ISSUE THREAD

**Issue by paronne** [ag-grid/ag-grid-enterprise#143]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Using the enterprise row model with grouping data, when the user quickly collapse/expand a group node the loading of child rows may not be resolved; if one of the request is not resolved, all subsequent requests (of other nodes too) are not resolved as well.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

The issue is reproducible also in the sample solution of the enterprise row model docs:
https://www.ag-grid.com/javascript-grid-enterprise-model/exampleEnterpriseSelection.html
To replicate quickly collapse/expand a group node; repeat several times until the "loading" of child rows hangs.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid-Enterprise version:** 13.0.2

* **Browser:** all

* **Language:** ES5

**Comment by rmc-software** [comment]
Thanks for bringing this to our attention. I have created AG-831 to track this.

**Comment by makinggoodsoftware** [comment]
Hi,

This is tracked by AG-831

Since this can be tracked from our pipeline we are going to close this issue

https://www.ag-grid.com/ag-grid-pipeline/



===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months.

As a result, we don’t have capacity to take feature requests from GitHub.e

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.

**Comment by JohnMasterson** [comment]
AG-831 was included in Version 16.

Regards, 

John
