### ISSUE TITLE
HeaderGroupComp is not exported

### ISSUE THREAD

**Issue by linvi** [ag-grid/ag-grid-enterprise#149]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

It is not currently possible to extend the default look and feel of a HeaderGroupComponent because they are not being exported.

``` js
export { IHeaderGroupParams, IHeaderGroup } from "./dist/lib/headerRendering/headerGroup/headerGroupComp";
```

As you can see `HeaderGroupComp` and `IHeaderGroupComp` are not part of the export. Which result in the inability to slightly change the default look and feel of HeaderGroups.

In our scenario we wanted to add a `tooltip` to the HeaderGroup.

**Expected behavior**

Have the ability to extend the `HeaderGroupComp` class.

**Minimal reproduction of the problem with instructions**

``` js
import { HeaderGroupComp } from "ag-grid/dist/lib/headerRendering/headerGroup/headerGroupComp";

export class MyHeaderComp extends HeaderGroupComp {
    public getGui(): HTMLElement {
        const htmlElement = super.getGui();
        // my custom changes
        return htmlElement;
    }
}
```

As you can see we need do not require `ag-grid` but `ag-grid/dist/lib/headerRendering/headerGroup/headerGroupComp`. This work on dev environment as we have access to the `node_modules`. But this will not work on release environment.

**What is the motivation / use case for changing the behavior?**

Extend the default styling but keeping the overall behaviour and logic.

**Please tell us about your environment:**

Windows 10 ; ag-grid-enterprise

* **ag-Grid version:** X.X.X

10.0.1 (same problem in latest)

* **Browser:**

ALL

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Typescript 2.3.3

**Comment by makinggoodsoftware** [comment]
Hi,

This is tracked by AG-1267

Since this can be tracked from our pipeline we are going to close this issue

https://www.ag-grid.com/ag-grid-pipeline/



===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months.

As a result, we don’t have capacity to take feature requests from GitHub.e

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
