### ISSUE TITLE
Excel Export styles for rowGroup'ed column are not getting applied

### ISSUE THREAD

**Issue by velidar** [ag-grid/ag-grid-enterprise#151]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Styles are missing from default grouping column (they are present on other columns) in excel exports.

**Expected behavior**

Styles should apply also to the grouping column in excel exports.

**Minimal reproduction of the problem with instructions**

Steps to check out the issue: open the [plunker](https://plnkr.co/edit/8doWVs4S3L1qfSBLHzMJ?p=preview) and execute right click on the grid -> Export -> Excel Export. 
You'll see then that the borders are missing from the default grouping column.

Added the following code (see main.js):
  - cellClassRules - 'excelRowClass' - set the callback to return true, so that the styles for id  'excelRowClass' apply everywhere
  - excelStyles - set styles for id 'excelRowClass' to continuous borderBottom and borderTop
  - set  rowGroup:true for the first column def

We are using ag-grid-react in our project, if that matters (I think not).

**What is the motivation / use case for changing the behavior?**

Our enterprise clients are heavily using excel exports. Though we've 'workarounded' the issue in our particular case by excluding the group column, they reported it to us as it presented styling glitches in the exports, so I thought I'd let you know.

**Please tell us about your environment:**
* **ag-Grid-Enterprise version:**  12.0.2, 13.3.1 (the plunker - still has the issue)

* **Browser:** all

* **Language:** all

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for raising this with use, we have created a ticket for this bug with id: AG-1389

Since this can be tracked from our pipeline we are going to close this issue

https://www.ag-grid.com/ag-grid-pipeline/



===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months.

As a result, we don’t have capacity to take feature requests from GitHub.e

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
