### ISSUE TITLE
[mouse middle click] have onRowClicked work with middle click

### ISSUE THREAD

**Issue by gabrielenosso** [ag-grid/ag-grid-enterprise#17]
Hi,
I think it would be a great option to have the possibility to "middle click" the rows (or cells).
Right now the events "onRowClicked" and "onCellClicked" are fired only when clicked with the left button.

It would be good if they would be always fired, so that the developer can manage what to do with the different buttons.
(Strangely, the cell is focused also when the middle button is clicked though)

**Comment by ceolter** [comment]
tracked by AG-183

**Comment by ceolter** [comment]
https://ag-grid.atlassian.net/browse/AG-183

**Comment by makinggoodsoftware** [comment]
Hi,

Closing this since it can be tracked from the pipeline

Thanks

===============

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

Bugs Raised Here:

We will do a periodic review of GitHub issues for any bugs raised and these can be tracked on our pipeline page: https://www.ag-grid.com/ag-grid-pipeline

Feature Requests/Support Raised Here:

We are reviewing how we process Feature Requests that come from GitHub. We currently have a very full pipeline of work which will be our priority for the coming months.

As a result, we don’t have capacity to take feature requests from GitHub.

We will review this as we move through our current backlog.

Thanks for your understanding.
ag-Grid Team.
