### ISSUE TITLE
Ag-grid Default context menu not appear in project

### ISSUE THREAD

**Issue by MrSatyam77** [ag-grid/ag-grid-enterprise#254]
Ag-grid context menu by right click only export item is display I need to appear copy,copy with header and paste item also.in short i need to ag-grid deafult-context menu on right click.I had already setup ag-grid enterprise with licence key.Please see my attached screen shot and give me solution
![ag-grid context menu](https://user-images.githubusercontent.com/43172491/85953030-21fc5880-b98b-11ea-8d02-e2924b62155c.png)

**Comment by fafeitsch** [comment]
Knowning that I'm a bit late to the party :), I had the same problem and found the solution.

I had to import the the ClipboardModule, too. See https://www.ag-grid.com/javascript-grid/modules/.

After importing the module, the respective menu entries were shown.

**Comment by kiril-matev** [comment]
Hi @MrSatyam77,

Thank you for opening this github issue.

**You opened this issue in a legacy repository instead of the main one, which is why we've not responded to it earlier.**

As this issue was submitted over a year ago and many improvements were made to the grid in this time, please upgrade to the latest version of AG Grid and verify whether you can still see this issue. If you still have this issue with the latest version, please submit a new github issue in the main AG Grid repository with a reproduction example.

**We will now close this issue and archive this repository soon to avoid any further confusion. If you want to open any new issues, please report them under the main repository to ensure they are processed promptly and seen by the entire AG Grid community:
https://github.com/ag-grid/ag-grid/issues**
