### ISSUE TITLE
Ag-grid 508 issue: Empty form label in table header

### ISSUE THREAD

**Issue by 53SubhaVellapandi** [ag-grid/ag-grid-enterprise#258]
**I'm submitting an 508 issue** 
Ag-grid 508 issue: Empty form label in table header

**Current behavior**
In table header select checkbox is binding to DOM element with ag-hidden property which doesn't have label inside.

**Expected behavior**
Either remove the hidden tags without binding to DOM elements Or include a dummy hidden value inside the hidden empty tag.

**Minimal reproduction of the problem with instructions**
Open ag-grid table in webpage
Press wave tool to check 508 Issue
One can find the Empty form label issue according to the number of column header in the table

**What is the motivation / use case for changing the behavior?**
To resolve the 508 compliance.

**Please tell us about your environment:**

* **ag-Grid-Enterprise version:** 23.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by kiril-matev** [comment]
Hi @53SubhaVellapandi!

Thank you for opening this github issue.

**You opened this issue in a legacy repository instead of the main one, which is why we've not responded to it earlier.**

As this issue was submitted almost 2 years ago and many improvements to accessibility were made to the grid in this time, please upgrade to the latest version of AG Grid and verify whether you can still see this issue. If you still have this issue with the latest version, please submit a new github issue in the main AG Grid repository with a reproduction example.

**We will now close this issue and archive this repository soon to avoid any further confusion. If you want to open any new issues, please report them under the main repository to ensure they are processed promptly and seen by the entire AG Grid community:
https://github.com/ag-grid/ag-grid/issues**
