### ISSUE TITLE
doing a paste with CMD+V causes the UI to jump

### ISSUE THREAD

**Issue by saurabhajmera** [ag-grid/ag-grid-enterprise#259]
**I'm submitting a bug**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The entire window scrolls to the top and then back to the row in which the contents were pasted.

**Expected behavior**
Pasting content into aggrid should not cause the scroll position to change.

**Minimal reproduction of the problem with instructions**
Step 1: Resize the window such that only the last few rows of the AgGrid are visible.
Step 2: Copy some text and paste it into the first cell of any visible row. I used a row from [this aggrid](https://plnkr.co/edit/?p=preview&preview) for my test
Step 3: Notice how the window scrolls to the top of the page and then back to the spot where you pasted the content

See this gif for more information.

![paste-jump](https://user-images.githubusercontent.com/1672671/99571287-ec7ef880-2987-11eb-876a-dae81c02a21e.gif)

Additionally, you can reproduce this issue using this stackblitz project : https://stackblitz.com/edit/react-ts-basic-ag-grid-n9z29x?file=index.tsx

**What is the motivation / use case for changing the behavior?**
This behavior results in poor user experience for users who have a small screen size and are used to copy and pasting content from excel or google sheets into the aggrid. 

**Please tell us about your environment:**
OS: Mac OS 10.15.5

* **ag-Grid-Enterprise version:** 2.0.X
ag-grid-enterprise 24.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome Version 86.0.4240.193

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 4.0.2

**Comment by kiril-matev** [comment]
Hi @saurabhajmera,


Thank you for opening this github issue.

**You opened this issue in a legacy repository instead of the main one, which is why we've not responded to it earlier.**

As this issue was submitted over a year ago and many improvements were made to the grid in this time, please upgrade to the latest version of AG Grid and verify whether you can still see this issue. If you still have this issue with the latest version, please submit a new github issue in the main AG Grid repository with a reproduction example.

**We will now close this issue and archive this repository soon to avoid any further confusion. If you want to open any new issues, please report them under the main repository to ensure they are processed promptly and seen by the entire AG Grid community:
https://github.com/ag-grid/ag-grid/issues**
