### ISSUE TITLE
Ctrl + z / y not working anymore with shown delete on user range selection

### ISSUE THREAD

**Issue by GoodMorgon** [ag-grid/ag-grid-enterprise#260]
Hello,

I followed the following blog post: https://blog.ag-grid.com/deleting-selected-rows-and-cell-ranges-via-key-press/ and it works... except that the ctrl + z / y buttons stop working then. 

If you select a range and delete it, you cannot undo your changes... 

It can be observed here: https://delete-rows-cells.stackblitz.io/

Is there a simple fix for this?

**Comment by kiril-matev** [comment]
Hi @GoodMorgon,

Thank you for opening this github issue.

**You opened this issue in a legacy repository instead of the main one, which is why we've not responded to it earlier.**

As this issue was submitted over a year ago and many improvements were made to the grid in this time, please upgrade to the latest version of AG Grid and verify whether you can still see this issue. If you still have this issue with the latest version, please submit a new github issue in the main AG Grid repository with a reproduction example.

**We will now close this issue and archive this repository soon to avoid any further confusion. If you want to open any new issues, please report them under the main repository to ensure they are processed promptly and seen by the entire AG Grid community:
https://github.com/ag-grid/ag-grid/issues**
