### ISSUE TITLE
Request for Sticky header

### ISSUE THREAD

**Issue by aydenxiao-gep** [ag-grid/ag-grid-enterprise#266]
[ ] bug report
[X] feature request
[ ] support request

**Expected behavior**
Sticky header

**Comment by kiril-matev** [comment]
Hello @aydenxiao-gep,

Thanks for requesting this.

This feature is now implemented:
https://www.ag-grid.com/javascript-data-grid/grouping-sticky-groups/

**This issue is in a legacy repository which will be archived soon. If you want to open any new issues, please report them under the main repository to ensure they are processed promptly and seen by the entire AG Grid community.**
