### ISSUE TITLE
Hiding empty header row column group in grid while maintaining hierarchy in Columns Tool Panel

### ISSUE THREAD

**Issue by ehamrin** [ag-grid/ag-grid-enterprise#268]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If a columnDefinition contains multiple column groups, but no grouped columns are visible in the grid, a header-row is still rendered for each level defined in columnDefinitions

**Expected behavior**
The div#ag-header-row-column-group should not be rendered if no columns that belong to a group have been selected.
Optionally with a flag `hideEmptyHeaderRows=true`

**Minimal reproduction of the problem with instructions**
```js
var columnDefs = [
  { headerName: 'Age', field: 'age' },
  {
    headerName: 'First level',
    children: [
      {
        headerName: 'Second level',
        children: [
          {
            headerName: 'Third level',
            children: [
              { headerName: 'Athlete', field: 'athlete', hide: true },
            ]
          }
        ]
      }
    ]
  }
]
```

**What is the motivation / use case for changing the behavior?**
We have a lot of columns not initially shown to the user. Most of them are grouped with various nesting levels, but not all of them. On initial render we only show the most common columns - those who are not nested. The result is 4 empty header rows since the more detailed columns aren't selected.

**Please tell us about your environment:**
Windows 10, NPM, Vue

* **ag-Grid-Enterprise version:** 25.3.0

* **Browser:** all

* **Language:** all

**Comment by kiril-matev** [comment]
Hello @ehamrin!

Thank you for bringing this up with us. 

The functionality you described wasn't part of the requirements when we built this feature. This is why we have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
**AG-7248 [Column Groups] Allow not displaying column group header rows for columns which aren't currently visible**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!
