### ISSUE TITLE
Is there any option to add multiple details grid under one master grid (Grouping -Master / Detail) ? 

### ISSUE THREAD

**Issue by Shaheedacholayil** [ag-grid/ag-grid-enterprise#272]

**Comment by kiril-matev** [comment]
Hi @Shaheedacholayil,

In order to provide multiple detail grids under the same master row, you need to use a custom detail presenter. In the custom detail presenter you can display multiple grids. 

You can see this demonstrated in our documentation here:
https://www.ag-grid.com/javascript-data-grid/master-detail-custom-detail/#custom-detail-with-grid

**You've opened this issue in a legacy repository which will be deleted soon. As we have now responded to this issue, I will now close it to avoid confusion. If you want to open any new issues, please do so under the main repository to ensure any issues you submit will be processed promptly and seen by the entire AG Grid community.**
