### ISSUE TITLE
Link is Invalid

### ISSUE THREAD

**Issue by rootux** [ag-grid/ag-grid-enterprise#274]
The readme link leads to 404
https://github.com/ag-grid/ag-grid/tree/master/packages/ag-grid-enterprise

**Comment by kiril-matev** [comment]
Hi @rootux,

**You opened this issue in a legacy repository instead of the main one, which is why we've not responded to it earlier.**

This broken link has since been fixed - note the link in the readme of this repository now correctly points to the main repository.
https://github.com/ag-grid/ag-grid-enterprise#readme

**This issue was opened in a legacy repository which was not monitored and this is why we have not responded to this earlier. We will archive this repository soon to avoid any further confusion. If you want to open any new issues, please report them under the main repository to ensure they are processed promptly and seen by the entire AG Grid community.**
