### ISSUE TITLE
Blank filter rows are not rendered

### ISSUE THREAD

**Issue by mahavirvataliya** [ag-grid/ag-grid-enterprise#275]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid-Enterprise version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

i am passing filtermodel
`
filterModel: {activity_type: {values: [""], filterType: "set"}}`

to the API. getting 3 records in response
No data gets rendered in agSetColumnFilter

I got 3 records there ]]]

![Screenshot 2021-12-24 at 4 04 50 PM](https://user-images.githubusercontent.com/10413703/147345403-67f5575c-5045-470e-bc3d-a44c5105bcb2.png)

![Screenshot 2021-12-24 at 4 05 16 PM](https://user-images.githubusercontent.com/10413703/147345430-878a7878-0a50-4947-8bc1-1a36660d9f08.png)

**Comment by kiril-matev** [comment]
Hi @mahavirvataliya,

You've submitted a bug report without following the bug template. In the future please submit a reproduction example and list of steps to reproduce the issue. You've also not specified the AG Grid version where the issue appears. This makes it hard to reproduce the issue.

The issue you've described was reported in AG Grid v26.2.

Here are the repro steps of this issue:
1. Open
https://plnkr.co/edit/4rQZkeXTTWOX8GGP?open=main.js
2. Open filter
3. Uncheck CELICA
**Actual**: No records shown
**Expected**: 3 records shown

This issue was fixed in v27.0 as you can see in example below:
https://plnkr.co/edit/MLGPOPzlCY3xJNBQ?open=main.js

Please upgrade to v27.0 or later to resolve this.

**You've reported this issue in a legacy repository which will be deleted soon. If you want to report any new issues, please report them under the main repository to ensure any issues you submit will be processed promptly and seen by the entire AG Grid community.**
