### ISSUE TITLE
FilterModel gets reset when user types case insensitive value

### ISSUE THREAD

**Issue by antran-mwb** [ag-grid/ag-grid-enterprise#277]
**I'm submitting a ...**  
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

My filterModel is getting reset when I supply a query string in the URL that doesn't belong in the filterParams.values.
For example if my filterParam.values = ['Hello', 'Yellow'].

When my user enters into the browser `www.myWebsite.com/?myColumn=_hello` the filterModel gets cleared out and the url ultimately becomes `www.myWebsite.com/?myColumn=_` and no filter is applied.

However, is the user types in `www.myWebsite.com/?myColumn=_Hello` it works perfectly fine. Is there a way to this be case insensitive? I was under the impression the filterParams had caseInsensitive set to False by default. Even explicitly setting doesn't do anything.

**Expected behavior**

It should set my filter to Hello regardless of the case sensitivity
`www.myWebsite.com/?myColumn=_hello`
`www.myWebsite.com/?myColumn=_Hello`

**Minimal reproduction of the problem with instructions**
```
{
    headerName: Colors
    headerTooltip: Colors
    lockVisible: true,
    colId: 'vehicle_color',
    field: 'vehicle_color',
    resizable: true,
    columnGroupShow: 'open',
    enableRowGroup: true,
    filter: true,
    filterParams: {
      values: ['Yellow', 'Red', 'Green', 'Blue', 'Magenta'],
    },
  },
```

**What is the motivation / use case for changing the behavior?**
This seems like it would be a normal use case as the customer can remember the column filter value, but may not remember it is case sensitive when they alter the url directly in the browser.

**Please tell us about your environment:**
Vue2 and WebStorm

* **ag-Grid-Enterprise version:** 2.0.X
V 23.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Happens in every browser

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6 and Javascript

**Comment by kiril-matev** [comment]
HI @antran-mwb,

Thank you for submitting this.

However, you've not followed the bug submission template and have not provided a live example reproducing the issue you reported. In particular, it's not clear how opening the page with a different URL is setting the filter model. Please provide a plunker where this different filterModel is set via a button above the grid. Also provide a clear description of the actual/expected behavior.

**You've submitted this issue in a repository which is legacy and will be deleted soon. This is why to avoid confusion I will now delete this issue. Please report this as a new issue following the bug template under the main repository to ensure any issues you submit will be processed promptly and seen by the entire AG Grid community.**
