### ISSUE TITLE
FillOperation callback should always be passed column and rowNode for current cell

### ISSUE THREAD

**Issue by The-MAZZTer** [ag-grid/ag-grid-enterprise#278]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When you are using the fill handle on AgGrid, if you are filling vertically the fillOperation callback will be given the column information but no information about the rows/cells being filled. If you are filling horizontally, you get the rowNode but not the information about each column. This information not provided is stripped out by FillHandle.prototype.processValues.

**Expected behavior**
FillHandle.prototype.processValues is called for each cell being filled and has the column and rowNode values relevant to the cell. So there's no reason the fillOperation can't get both values. The identity of the cell might be desired to influence the fill operation.

**Minimal reproduction of the problem with instructions**

https://raw.githubusercontent.com/ag-grid/ag-grid-enterprise/master/dist/ag-grid-enterprise.js

```javascript
            var userResult = userFillOperation({
                event: event,
                values: values,
                initialValues: initialValues,
                currentIndex: idx,
                currentCellValue: this.valueService.getValue(col, rowNode),
                api: this.gridOptionsWrapper.getApi(),
                columnApi: this.gridOptionsWrapper.getColumnApi(),
                context: this.gridOptionsWrapper.getContext(),
                direction: direction,
                column: isVertical ? col : undefined,
                rowNode: !isVertical ? rowNode : undefined // only present if left / right
            });
```

Currently column and rowNode properties are cleared out depending on the direction of the fill.

Here is my proposed change:

```javascript
            var userResult = userFillOperation({
                event: event,
                values: values,
                initialValues: initialValues,
                currentIndex: idx,
                currentCellValue: this.valueService.getValue(col, rowNode),
                api: this.gridOptionsWrapper.getApi(),
                columnApi: this.gridOptionsWrapper.getColumnApi(),
                context: this.gridOptionsWrapper.getContext(),
                direction: direction,
                column: col,
                rowNode: rowNode
            });
```

**What is the motivation / use case for changing the behavior?**
There are use cases for wanting full access to column and rowNode regardless of fill direction.

For example:

I have an aggrid with two columns. Both are editable using the rich seelct dropdown.

The first has two possible values in the dropdown.

The second uses cellEditorSelector to generate a dynamic list of valid values, depending on the option selected in the first dropdown for a particular row.

I want to limit the values the user can enter via fill operation to match valid values for any dropdown in the specific cell.. Invalid values will be cleared.

Currently, I cannot tell both what column the user is filling when filling horizontally so I cannot determine if I should block a fill based on invalid values being entered. When filling vertically, it's not possible for me to validate the value against the value list since I do not know which rowNode I am in.

**Please tell us about your environment:**
Windows 10 x64 20H2
Node 14.19.0
Angular 8.3.23
AgGrid 22.1.2  (I verified on the latest trunk code as well)
Chrome Version 100.0.4896.127 (Official Build) (64-bit)
TypeScript 3.4.5

**Comment by kiril-matev** [comment]
Hi @The-MAZZTer,

Thanks for reaching out.

**You opened this issue in a legacy repository instead of the main one, which is why we've not responded to it earlier.**

The latest version of AG Grid provides the column and row in the params of the fill operation callback regardless of the direction the fill handle is used in. See this here:
https://github.com/ag-grid/ag-grid/blob/4f7e82d54cb0ff9b59d7bd20bb177a9bc71c23cc/enterprise-modules/range-selection/src/rangeSelection/fillHandle.ts#L301

You can also verify this in this example:
1. Open
https://plnkr.co/edit/Bi3XWY1Mq3jw3CMK?open=main.js
2. Open console
3. Click top-left grid cell 
4. Drag the fill handle two cells to the right
5. Inspect the console messages with params provided to the fill operation
Actual & Expected: Each message params includes the columns that are filled in
6. Click top-left grid cell 
7. Drag the fill handle two cells down 
8. Inspect the console messages with params provided to the fill operation
Actual & Expected: Each message params includes the rows that are filled in

Please upgrade to the latest version of AG Grid to benefit from this.

**We will now close this issue and archive this repository soon to avoid any further confusion. If you want to open any new issues, please report them under the main repository to ensure they are processed promptly and seen by the entire AG Grid community:**
**https://github.com/ag-grid/ag-grid/issues**
