### ISSUE TITLE
FillOperation callback should be provided with the proposed new fill value

### ISSUE THREAD

**Issue by The-MAZZTer** [ag-grid/ag-grid-enterprise#279]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently if you define a fill operation the callback is run before aggrid calculates a default fill values for each cell. If the callback returns false only then is the next cell value calculated.

If the user wants to inspect what value aggrid would give the cell, the user must copy the aggrid source code for calculating this value. This is not desired since this code may change with future aggrid versions making the copy obsolete.

**Expected behavior**
It would be nice if this value was calculated first and passed into the callback. Then the callback could see if it is not a desired value and replace it, rather than having to work from scratch.

**Minimal reproduction of the problem with instructions**
The code with the current  behavior is in FillHandle.prototype.processValues in https://raw.githubusercontent.com/ag-grid/ag-grid-enterprise/master/dist/ag-grid-enterprise.js.

The second half of the function where the value is calculated should be moved to the top and assigned to a varaible rather than returned. This value should be passed into the fill operation callback.

**What is the motivation / use case for changing the behavior?**
The user may want to inspect the default value and change it if desired.

For example ~~currently~~ the string value "01 - NEW" will get a next value of "NaN". ~~This is a bug in and of itself which I will file separately.~~ Edit: This bug appears fixed in the latest version. It is difficult for me to determine this result without copying the AgGrid source code for calculating this value.

**Please tell us about your environment:**
Windows 10 x64 20H2
Node 14.19.0
Angular 8.3.23
AgGrid 22.1.2 (I verified on the latest trunk code as well)
Chrome Version 100.0.4896.127 (Official Build) (64-bit)
TypeScript 3.4.5

**Comment by kiril-matev** [comment]
Hi @The-MAZZTer!


Hi @theorare,

Thank you for opening this github issue.

**You opened this issue in a legacy repository instead of the main one, which is why we've not responded to it earlier.**

Please when requesting changes in functionality illustrate the current/desired behavior with an example and clear descriptions of what the behavior is now and how you'd like to change it by referring to the example. I built an example for the fill handle with a custom fill operation but cannot understand what the requirement is.
https://plnkr.co/edit/rhOs8RwesDz2VzjG?open=main.js

Please submit a new github issue in the main AG Grid repository following the instructions above.
https://github.com/ag-grid/ag-grid/issues

**We will now close this issue and archive this repository soon to avoid any further confusion. If you want to open any new issues, please report them under the main repository to ensure they are processed promptly and seen by the entire AG Grid community.**
