### ISSUE TITLE
Last sparkline tooltip renderer overrides others

### ISSUE THREAD

**Issue by selenecodes** [ag-grid/ag-grid-enterprise#290]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When you have multiple columns of sparklines and wish to add separate tooltip types the tooltip renderer setting is ignored and simply uses the last assigned tooltip renderer.

**Expected behavior**
Let separate sparkline columns have separate tooltips if desired.

**Minimal reproduction of the problem with instructions**

[Reproduction case on ObservableHQ.com](https://observablehq.com/d/3ebbcf65d33387f4)

**What is the motivation / use case for changing the behavior?**

Right now sparkline tooltips are unusable if one has to format the value inside the sparkline. E.g. if you would want log10 vs normal formatting for different sparklines you simply can't. An easy fix would be to expose the column name so that one could format conditionally based on that. The best option would ofcourse be to fix the underlying issue of tooltip renderers being overwritten.

**Please tell us about your environment:**

* **ag-Grid-Enterprise version:** 27.3.0

* **Browser:** Firefox 100.01, Chrome 101.0.4951.67 (Official Build) (64-bit) (cohort: Stable) 

* **Language:** all

**Comment by kiril-matev** [comment]
Hello @selenecodes!

Thank you for bringing this up with us. 

The functionality you described wasn't part of the requirements when we built this feature. This is why we have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
**AG-6716 [Sparklines] Allow per-column tooltip instances for sparklines**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

**This issue is opened in a legacy repository which will be deleted soon. As we've now responded to this, this issue will be closed to avoid any confusion. If you want to report any new issues, please report them under the main repository to ensure any issues you submit will be processed promptly and seen by the entire AG Grid community.**

Thanks again for bringing this up with us - we appreciate your time!
