### ISSUE TITLE
Grouping: Group a column of arrays by each item. (Example, Group by Tags where cellValue=[a, b, c] and it should group by a, b, and c)

### ISSUE THREAD

**Issue by ajitkayastha** [ag-grid/ag-grid-enterprise#291]
**I'm submitting a ...
```
[x] feature request
```

**Current behavior**

**Expected behavior**
Group a column of arrays by each item. (Example, Group by Tags where cellVlaue=[a, b, c] and it should group by a, b, and c).

**Minimal reproduction of the problem with instructions**
Create a AGgrid Table with Grouping enabled. One or more columns may  have value as array of strings (e.g. tags:[a, b, c]) While grouping by tags currently it groups by "a , b, c".  We require it to group tags by "a", "b" and "c".

**What is the motivation / use case for changing the behavior?**
This is motivated from a significant use case where a each row of data may have a column with various tags. We need to group data by each tag separately.

**Please tell us about your environment:**
React JS

* **ag-Grid-Enterprise version:** 2.0.X
yes

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All Web Browsers

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by kiril-matev** [comment]
Hello @ajitkayastha!

Thank you for opening this github issue.

**You opened this issue in a legacy repository instead of the main one, which is why we've not responded to it earlier.**

In the future, please illustrate your requirements with an example - this makes it much clearer.

Consider this example:
https://plnkr.co/edit/Ej2PYRuGf7GWiBMA?open=main.js

Note the country column has array values. If the grid groups in the way you've described this will result in the following resultset:
Bulgaria
                John
Jamaica
                Damien
United Kingdom
                John
                Peter
United States
               Peter
               Damien

However, this isn't a just grouping operation, this is a data transformation which unfolds the initial (condensed) dataset, and expands it into the following before grouping. The data transformation unfolds the dataset into this before grouping:
John     Bulgaria
John     United Kingdom
Peter     United States
Peter     United Kingdom
Damien Jamaica
Damien United States

The grid doesn't know the structure of your data. Making such a transformation involves making assumptions which the grid shouldn't be doing. The only way to implement this is for you to use the grid API, handle the rowGroupChanged and when the user is grouping by the COUNTRY column, expand (unfold) the dataset manually, then group by it, and when the user removes the COUNTRY column from the grouping to revert to the condensed (folded) dataset where instead of the 6 rows above with a single country value per row, you have 3 rows with 2 country values per row.

This is an application-level concern and you should implement this in your code as the grid cannot make assumptions about the structure of your data.

**In the future, please submit github issues in the main AG Grid repository:
https://github.com/ag-grid/ag-grid/issues

We will now close this issue and archive this repository soon to avoid any further confusion. If you want to open any new issues, please report them under the main repository to ensure they are processed promptly and seen by the entire AG Grid community.**
