### ISSUE TITLE
Comparators not working as expected on grouped columns

### ISSUE THREAD

**Issue by Sonya-M** [ag-grid/ag-grid-enterprise#292]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When grouping by a column with a custom comparator, that comparator is used when sort is applied on any column with an aggregation function, unless that column has its own comparator. This results in potential errors if the grouping column comparator is not compatible with the aggregated column (see [demo](https://plnkr.co/plunk/blzppQrhQYdmQXnR) ).

**Expected behavior**
Custom comparator should only be applied to the column for which it is defined

**Minimal reproduction of the problem with instructions**

- enable grouping for a column with a custom comparator function
- while grouping by that column, apply sort on some other column with an aggregation function.
- see demo based on group sorting example [here](https://plnkr.co/plunk/blzppQrhQYdmQXnR) 

**What is the motivation / use case for changing the behavior?**

To be able to apply sort to any column in the grid

**Please tell us about your environment:**

* **ag-Grid-Enterprise version:** 27.3.0

* **Browser:** [all ]

* **Language:** [TypeScript]

**Comment by kiril-matev** [comment]
Hi @Sonya-M,

Thank you for reporting this.

This issue was resolved in AG Grid 28.0.

Please see this working as expected in v28.1.3 using the steps below:
1. Open
https://plnkr.co/edit/6HuRMWdwSKwT8YwD?open=main.js
2. Sort on the TOTAL column
**Actual & Expected**: TOTAL column sorted ascending, values displayed in ascending order

**This AG Grid repository is legacy and will be deleted soon. If you want to report any new issues, please report them under the main repository to ensure any issues you submit will be processed promptly and seen by the entire AG Grid community.**
