### ISSUE TITLE
when i am setting :rowData="rowData" in ag grid setRowData is not working and when removing :rowData="rowData" setRowData is working fine why 

### ISSUE THREAD

**Issue by rahulparashar07** [ag-grid/ag-grid-enterprise#293]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-Grid-Enterprise version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by kiril-matev** [comment]
Hello @rahulparashar07!

Thank you for opening this github issue.

**You opened this issue in a legacy repository instead of the main one, which is why we've not responded to it earlier.**

When submitting this issue, you've not followed our bug report template. Specifically, you've not included a live plunker/standalone example reproducing the issue. Please upgrade to the latest version of AG Grid and verify whether you can still see this issue. If you still have this issue with the latest version, please submit a new github issue in the main AG Grid repository with a reproduction example:
https://github.com/ag-grid/ag-grid/issues

**We will now close this issue and archive this repository soon to avoid any further confusion. If you want to open any new issues, please report them under the main repository to ensure they are processed promptly and seen by the entire AG Grid community.**
