### ISSUE TITLE
CSV Injection vulnerability

### ISSUE THREAD

**Issue by thel0ner** [ag-grid/ag-grid-enterprise#294]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => CSV Injection vulnerability 
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**exportDataAsCsv** method does not sanitize data for Formula injection.
**Expected behavior**

It's safe to expect the grid to control data before exporting a CSV file, therefore user won't be faced with malicious codes in exported CSV file by the grid.
**Minimal reproduction of the problem with instructions**
Sample payload to test:  `@SUM(1+9)*cmd|' /C calc'!A0`
[resource on OWASP](https://owasp.org/www-community/attacks/CSV_Injection)

Sample code to solve it: 
`
export const csvXlsxFormulaInjectionSanitizer = (str: string): string => {
    if (str !== null && str.match(/^[=@+-]/)) {
        return `"'${str.replace(/"/g, '""')}"`;
    }
    return str;
}
`

**What is the motivation / use case for changing the behavior?**

Safety.
**Please tell us about your environment:**
HTTP Server: IIS / Apache / Nginx

Angular version 13.x 
* **ag-Grid-Enterprise version:** 25.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [TypeScript 4.1.5 |]

**Comment by kiril-matev** [comment]
Hello @thel0ner,

**You opened this issue in a legacy repository instead of the main one, which is why we've not responded to it earlier.**

AG Grid generates CSV exports based on data shown in the grid, and doesn't do any processing of this data before it generates the CSV file. We're not planning on providing additional value processing as part of the built-in CSV exporter to filter out any malicious content in grid cells.

If you'd like to filter out any code injection project grid cell value, please use the processCellCallback in the CSV export options to process each value as it gets exported:
https://www.ag-grid.com/javascript-data-grid/csv-export/#reference-CsvExportParams-processCellCallback

This way you can implement your logic to modify cell values and prevent any malicious code from getting exported. 

**We will now close this issue and archive this repository soon to avoid any further confusion. If you want to open any new issues, please report them under the main repository to ensure they are processed promptly and seen by the entire AG Grid community.**
